### ISSUE TITLE
Cannot convert undefined or null to object in getSuccessResponse

### ISSUE THREAD

**Issue by kirill-konshin** [yarax/swagger-to-graphql#20] opened 2017-05-10 21:12 UTC
```
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getSuccessResponse (/xxx/node_modules/swagger-to-graphql/lib/swagger.js:21:10)
```

Swagger-to-graphql version is 1.0.5.

The schema that I have used: https://raw.githubusercontent.com/tylerlong/rc-codegen/master/common/swagger.json

The schema has been validated with https://github.com/Yelp/swagger_spec_validator.

**Comment by alexpit** [comment] 2017-05-12 21:14
Looks like a duplicate of https://github.com/yarax/swagger-to-graphql/issues/15

**Comment by kirill-konshin** [comment] 2017-05-12 21:24
Nope, it's a different thing, it's a wrong assumption about the spec.

**Comment by alexpit** [comment] 2017-05-12 21:29
It seems to be a failure at precisely the same code line `swagger.js:21:10`, so unless you describe what different spec assumption was made (different from "there cannot be any parameters under a path"), it's not entirely clear how this issue is different.

**Comment by kirill-konshin** [comment] 2017-05-12 21:33
Pls disregard my previous comment, I was looking at a different bug #18... Yes, looks like this issue is a duplicate.

**Closed** 2017-06-14 14:47 UTC
